### ISSUE TITLE
[Request] Add GPLv3 License

### ISSUE THREAD

**Issue by FireMario211** [wlagos3/percentage-bugfix#1]
Recently I came across this repository, and found that some of the lines in the `main.cpp` file, was taken without credit. While I do not mind my code being taken as long as I at least receive credit for it, what does bother me though is that this repository does not include any license.

The affecting code I am referring to is this line:
https://github.com/wlagos3/percentage-bugfix/blob/8e813669fb8c58e43f4326847f261b52ae99b5ee/src/main.cpp#L10-L23

This code is taken from the **[Golden Best](https://github.com/FireMario211/Golden-Best)** mod, specifically these lines:
https://github.com/FireMario211/Golden-Best/blob/fae9033b781e00ecb86557426fad8e68d19b4ba5/src/main.cpp#L10-L24

As the original author and copyright holder of the code, I request that you do one of the following:
1. Add the GPLv3 license to the repository and possibly credit me.
2. Remove my code from the mod and rewrite it.

Any other license besides GPLv3 is not compatible.

Thank you.

**Comment by wlagos3** [comment]
Hey! I'm very new to this type of thing and I figured since your mod was open source and the code was decently simple it was ok to copy. I'm happy to give you credit and select the proper license.

**Comment by FireMario211** [comment]
:+1:
